version: '3.8'

services:
  mongodb:
    image: mongo:6.0.3
    container_name: mongodb_local
    restart: always
    ports:
      - '${DB_PORT:-27017}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-my_user}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-password123}
      - MONGO_INITDB_DATABASE=${DB_DB:-mydb}
    volumes:
      - mongodblocal:/data/db

volumes:
  mongodblocal:
